# CRUD OPERATIONS IN MYSQL
# CREATE Database
create database rakuten;
use rakuten;
Create table employee(Name varchar(30) not null, Age Integer);
Insert into employee (Name,Age) values("Harry",20),("Ravi",32),("Sam",23);
select * from employee;
drop table employee;
select * from employee;
show databases;
use rakuten;
create table ofcData(Name varchar(30),salary Integer,Age integer);
show tables;
Insert into ofcData (Name,salary,Age) values("Harry",5000,20),("Ravi",2800,32),("Sam",8000,23);
select * from ofcData;
alter table ofcData change salary expenses int;
select * from ofcData;
Insert into ofcData (Name,expenses,Age) values ("Sreenu",5400,22),("Mahesh",4509,21),("arjun",3400,19);
select * from ofcData where Age<23;
# Type of Operations
select Name,(expenses*0.5),Age from ofcData ;
select Name,(expenses+100),Age from ofcData;
select * from ofcData where Age in (1,19,23,22,21);
select * from ofcData where Age between 20 and 30;
select * from ofcData where Age >20 and Age<= 30;
select * from ofcData where Name like '%a';
select * from ofcData where Name like '%a%';
select * from ofcData where Name like '%h';
select * from ofcData order by expenses;
select * from ofcData order by expenses desc;
Insert into ofcData (Name,expenses,Age) values ("yash",7400,22),("Bindu",4709,21),("Siva",6800,19);
select distinct Age from ofcData;
select distinct Name,Age from ofcData;
select upper(Name) from ofcData;
select lower(Name) from ofcData;
select concat(Name,' San') from ofcData;
select length(Name),Name from ofcData;
select Name,substr(Name,1,4) from ofcData;
select Name ,instr(Name,'a') from ofcData;
select trim('h' from 'harry');
select trim('h' from Name) from ofcData;
select ltrim(' Rakuten symphony');
select rtrim(' Rakuten symphony ');
select Name,replace(Name,'A','*') from ofcData;
select Name,Age, round((expenses*0.556),2) from ofcData;
select mod(20,3);
select now();
select current_date();
select current_time();
select user();
select datediff('2022-05-28','1999-05-10');
# Joins
create table selfData(Name varchar(30), Salary Integer,Age integer);
Insert into selfData (Name,Salary,Age) values ("Sreenu",54000,22),("Mahesh",45090,21),("arjun",34000,19);
Insert into selfData (Name,Salary,Age) values ("yash",74000,22),("Bindu",47090,21),("Siva",68000,19);
select * from selfData;
select e.Name,e.Salary from selfData e join ofcData d on e.Age=d.Age;
select e.Name,e.Salary from selfData e right join ofcData d on e.Age=d.Age;
select e.Name,e.Salary from selfData e left join ofcData d on e.Age=d.Age;
select e.Name,e.Salary from selfData e right outer join  ofcData d on e.Age=d.Age;
select e.Name,d.Name from selfData e natural join ofcData d where e.Age=d.Age; 
commit;